In [12]:
import pandas as pd
import requests
import numpy as np
import matplotlib.pyplot as plt
import gmaps
from config import gkey
import os
from scipy.stats import linregress

In [13]:
#gkey = "AIzaSyDiQ6ibaZs3DBrKJMfTNkM8oP0UPnWecoc"
gmaps.configure(gkey)

In [14]:
datafile = 'Provided City weather data.csv'

In [15]:
citi_df = pd.read_csv(datafile)
citi_df.head()

,City_ID,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,0,ostrovnoy,2,RU,1558378754,72,68.05,39.51,37.50,7.16
1,1,mahebourg,75,MU,1558378503,74,-20.41,57.70,78.80,11.41
2,2,qaanaaq,25,GL,1558378755,73,77.48,-69.36,22.20,2.37
3,3,zhuhai,0,CN,1558378755,39,40.71,112.04,44.60,4.47
4,4,cape town,20,ZA,1558378755,76,-33.93,18.42,55.99,8.05

In [16]:
filter1 = citi_df["Cloudiness"] <= 0 
filter2 = citi_df["Wind Speed"] < 10 
filter3 = citi_df["Max Temp"] > 70
filter4 = citi_df["Max Temp"] < 80

vacation_cities_df = citi_df.loc[filter1 & filter2 & filter3 & filter4].copy()
vacation_cities_df

,City_ID,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
7,7,opuwo,0,NaN,1558378523,23,-18.06,13.84,72.06,5.44
70,70,ponta do sol,0,BR,1558378767,57,-20.63,-46.00,73.68,5.32
88,88,cidreira,0,BR,1558378770,66,-30.17,-50.22,76.56,5.50
138,138,morondava,0,MG,1558378780,69,-20.30,44.28,79.08,9.06
139,139,vaini,0,IN,1558378780,88,15.34,74.49,78.90,1.59
176,176,nador,0,MA,1558378499,40,35.17,-2.93,75.20,6.93
297,297,mogok,0,MM,1558378844,51,22.92,96.51,72.24,2.77
444,444,birjand,0,IR,1558378880,26,32.86,59.22,71.60,9.17

In [17]:
url ="https://maps.googleapis.com/maps/api/place/nearbysearch/json"

vacation_cities_df["Hotel Name"] = ""

for idx, row in vacation_cities_df.iterrows():
    print("Getting hotel name for: ", row['City'], row['Lat'], row['Lng'])
    target_coordinates = f"{row['Lat']},{row['Lng']}"
    target_location = row['City']
    target_radius = 5000
    target_types = "lodging"

    params = {

        "location":target_coordinates,
        "place":target_location,    
        "types": target_types,
        "radius": target_radius,
        "key" : gkey   
    }
    
    vacation_place = requests.get(url,params).json()
    hotel_name = vacation_place["results"][0]["name"]
    print(vacation_place["results"][0]["name"])
    print(vacation_place["results"][0]["vicinity"])
    
    vacation_cities_df.loc[idx, "Hotel Name"] = hotel_name
    print(hotel_name)
    print()

Getting hotel name for:  opuwo -18.06 13.84
ABBA Guesthouse
Muharukua Ave, Opuwo
ABBA Guesthouse

Getting hotel name for:  ponta do sol -20.63 -46.0
Hotel Escarpas do Lago
Avenida das Caravelas, 25 - Engenheiro José Mendes Júnior, Capitólio
Hotel Escarpas do Lago

Getting hotel name for:  cidreira -30.17 -50.22
Pond Country Club
Estrada RS 784 KM 7 - Lagoa, Cidreira
Pond Country Club

Getting hotel name for:  morondava -20.3 44.28
La Case Bambou
Nosy kely, Morondava
La Case Bambou

Getting hotel name for:  vaini 15.34 74.49
Dandeli Lake County
Dandeli, Jagalbet
Dandeli Lake County

Getting hotel name for:  nador 35.17 -2.93
Hôtel La Giralda
Avenue Des Far, Nador
Hôtel La Giralda

Getting hotel name for:  mogok 22.92 96.51
MOGOK HILL HOTEL
Anawrahta Street (Near Tennis Court), Bogone Quarter, Mogok
MOGOK HILL HOTEL

Getting hotel name for:  birjand 32.86 59.22
تاکسی سرویس آرامش
Birjand, خیابان مدرس ۱۱
تاکسی سرویس آرامش

In [18]:
vacation_cities_df

,City_ID,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed,Hotel Name
7,7,opuwo,0,NaN,1558378523,23,-18.06,13.84,72.06,5.44,ABBA Guesthouse
70,70,ponta do sol,0,BR,1558378767,57,-20.63,-46.00,73.68,5.32,Hotel Escarpas do Lago
88,88,cidreira,0,BR,1558378770,66,-30.17,-50.22,76.56,5.50,Pond Country Club
138,138,morondava,0,MG,1558378780,69,-20.30,44.28,79.08,9.06,La Case Bambou
139,139,vaini,0,IN,1558378780,88,15.34,74.49,78.90,1.59,Dandeli Lake County
176,176,nador,0,MA,1558378499,40,35.17,-2.93,75.20,6.93,Hôtel La Giralda
297,297,mogok,0,MM,1558378844,51,22.92,96.51,72.24,2.77,MOGOK HILL HOTEL
444,444,birjand,0,IR,1558378880,26,32.86,59.22,71.60,9.17,تاکسی سرویس آرامش

In [19]:
marker_locations = vacation_cities_df [ ["Lat","Lng"] ]
city_humidity = vacation_cities_df[ "Humidity" ]
marker_hotel_names = vacation_cities_df["Hotel Name"]
marker_city_names = vacation_cities_df["City"]
marker_country_codes = vacation_cities_df["Country"]


figure_layout ={
    'width':'400px',
    'Height': '100px',
    'border': '1px solid black',
    'padding':'1px',
    'margin': '0 Auto 0 Auto'
}

fig = gmaps.figure(layout = figure_layout)

heat_layer = gmaps.heatmap_layer(marker_locations, weights=city_humidity, dissipating = True, max_intensity = 10, point_radius =10)
fig.add_layer(heat_layer)

markers = gmaps.marker_layer(marker_locations,
    info_box_content = [f"<B>Hotel: </b>{hotel}<BR><B>City:</b> {city}<BR><B>Country:</b> {country}" for hotel, city, country in zip(marker_hotel_names, marker_city_names, marker_country_codes) ])
fig.add_layer(markers)

fig

Figure(layout=FigureLayout(border='1px solid black', height='420px', margin='0 Auto 0 Auto', padding='1px', wi…